### ISSUE TITLE
SVR doesn't seem to work properly

### ISSUE THREAD

**Issue by pchronz** [mpastell/LIBSVM.jl#14]
Hi @simonster,

neither epsilon-SVR nor nu-SVR seem to work properly. Here's an example:

```
import PyPlot
import LIBSVM

N = 150
X = reshape(collect(1:float(N)), N, 1)
y = reshape(map(x->x^2, X), N)
idx = collect(1:N)
shuffle!(idx)
X_tr = X[idx[1:120], :]
y_tr = y[idx[1:120]]
X_test = X[idx[121:end], :]
y_test = y[idx[121:end]]

svm = LIBSVM.svmtrain(y_tr, X_tr'; svm_type=Int32(4), C=1000.)
y_pr_tr = LIBSVM.svmpredict(svm, X_tr')[1]
y_pr_test = LIBSVM.svmpredict(svm, X_test')[1]

PyPlot.scatter(X_tr, y_tr; color="blue")
PyPlot.scatter(X_tr, y_pr_tr; color="red")
PyPlot.scatter(X_test, y_pr_test; color="green")
PyPlot.show()
```

That code results in the following plot:
![svr-fail](https://cloud.githubusercontent.com/assets/586138/15174476/2d54aec8-1762-11e6-814c-bbc1d143d9cb.png)

The training points in red are predicted seemingly perfectly. The predictions on the test set are scattered though.
Playing around with the parameters doesn't seem to make it any better. In fact, some combinations of parameters lead to errors. For example,

`svm = LIBSVM.svmtrain(y_tr, X_tr'; svm_type=Int32(4), C=1000., gamma=0.01)`

leads to

> ERROR: LoadError: BoundsError: attempt to access 120-element Array{Float64,1}:
>  16129.0
>  16384.0
>   6241.0
>   9409.0
>    121.0
>  11236.0
>   4624.0
>      4.0
>   4489.0
>   3025.0
>      ⋮  
>  17689.0
>   5929.0
>  21316.0
>   1681.0
>      9.0
>   2809.0
>   9604.0
>   2601.0
>   1764.0
>   at index [128]
>  in svmpredict at /home/peter/.julia/v0.4/LIBSVM/src/LIBSVM.jl:365
>  in include at ./boot.jl:261
>  in include_from_node1 at ./loading.jl:320
>  in process_options at ./client.jl:280
>  in _start at ./client.jl:378
> while loading /home/peter/dev/jlearn/sandbox.jl, in expression starting on line 15

.

**Comment by mpastell** [comment]
This is now fixed in master
