### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by staticfloat** [mpastell/LIBSVM.jl#19]
@simonster The latest release on METADATA is from 2014, and doesn't work on Julia v0.5 anymore.  Can we cut a new release?

**Comment by simonster** [comment]
Sure. I don't have time to do any kind of QA at the moment, but I gave you commit access and enabled Attobot, so if current master is working for you, feel free to create a release.

**Comment by mpastell** [comment]
I would also appreciate a new release. It would probably be better to update for 0.6 first. I can do it if you want.

**Comment by mpastell** [comment]
I have now fixed warnings and `svmcv` on 0.5 and 0.6 in #20

**Comment by mpastell** [comment]
A tag is now pending https://github.com/JuliaLang/METADATA.jl/pull/8919

**Comment by mpastell** [comment]
v0.1.0 is now tagged
