### ISSUE TITLE
"int32 not defined" when trying to use LIBSVM

### ISSUE THREAD

**Issue by xlambein** [mpastell/LIBSVM.jl#21]
Hello,

I installed the package using `Pkg.add`, which worked fine, but when I try to use it with: `using LIBSVM`, I get the following error:
```julia
julia> using LIBSVM
ERROR: LoadError: UndefVarError: int32 not defined
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/xlambein/.julia/v0.5/LIBSVM/src/LIBSVM.jl, in expression starting on line 5
```
Do you have any idea what I might be doing wrong?

**Comment by rdeits** [comment]
The latest tagged release of LIBSVM.jl is very old and doesn't work on Julia v0.5. Hopefully that will be fixed soon. See: #19 

You can get the latest version right now by doing `Pkg.checkout("LIBSVM")` and restarting Julia.

**Comment by mpastell** [comment]
v0.1.0 has been tagged and this is now fixed.
