### ISSUE TITLE
Support Julia 1.0

### ISSUE THREAD

**Issue by DilumAluthge** [mpastell/LIBSVM.jl#42]
Currently, `import LIBSVM` works on Julia 0.6 and Julia 0.7, but fails on Julia 1.0.

Could we add support for using LIBSVM.jl on Julia 1.0?

cc: @mpastell

**Comment by mpastell** [comment]
I think the failures on 1.0 is due to LIBLINEAR https://github.com/innerlee/LIBLINEAR.jl . Maybe you could help @innerlee to update it if he doesn't have time.

**Comment by innerlee** [comment]
I will bring my packages up to date some time this week, thanks for the friendly reminder

**Comment by innerlee** [comment]
LIBLINEAR.jl has updated to support Julia 1.0

**Comment by mpastell** [comment]
Thanks @innerlee!

**Comment by DilumAluthge** [comment]
Thank you so much @innerlee and @mpastell

**Comment by DilumAluthge** [comment]
@innerlee and @mpastell I can confirm that LIBSVM and LIBLINEAR work on Julia 1.0. Thank you both.
