### ISSUE TITLE
julia crush when using LIBSVM on large datasets

### ISSUE THREAD

**Issue by helloinrm** [mpastell/LIBSVM.jl#51]
Hi,
It happens to me that julia will crush when using LIBSVM for classification on large datasets. In Juno, the error happens when the dataset is 2000*2000 artificial random generated. In cmd, the error happens when dataset is 10000*10000.

Here's the bug report:

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffea53ba5a9 -- svm_predict_values at C:\Users\inrm\.julia\packages\LIBSVM\5Z99T\deps\libsvm.dll (unknown line)
in expression starting at E:\Coder\github\qisvm\qisvm.jl:705
svm_predict_values at C:\Users\inrm\.julia\packages\LIBSVM\5Z99T\deps\libsvm.dll (unknown line)
vcomp_fork at C:\Windows\SYSTEM32\VCOMP140.DLL (unknown line)
vcomp_fork at C:\Windows\SYSTEM32\VCOMP140.DLL (unknown line)
vcomp_fork at C:\Windows\SYSTEM32\VCOMP140.DLL (unknown line)
svm_predict_values at C:\Users\inrm\.julia\packages\LIBSVM\5Z99T\deps\libsvm.dll (unknown line)
#svmpredict#4 at C:\Users\inrm\.julia\packages\LIBSVM\5Z99T\src\LIBSVM.jl:435
svmpredict at C:\Users\inrm\.julia\packages\LIBSVM\5Z99T\src\LIBSVM.jl:402
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
svm3 at E:\Coder\github\qisvm\qisvm.jl:362
competition at E:\Coder\github\qisvm\qisvm.jl:692
competition at E:\Coder\github\qisvm\qisvm.jl:670
unknown function (ip: 0000000001E34E8E)
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:328
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:764
jl_interpret_toplevel_thunk_callback at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:888
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000038CDAD0F)
unknown function (ip: 0000000000000002)
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:873
include_string at .\loading.jl:1075
#200 at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:166
withpath at C:\Users\inrm\.julia\packages\CodeTools\kosGY\src\utils.jl:30
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
withpath at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:9
#199 at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:163 [inlined]
with_logstate at .\logging.jl:395
with_logger at .\logging.jl:491 [inlined]
#198 at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:162 [inlined]
hideprompt at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\repl.jl:141
macro expansion at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:161 [inlined]
macro expansion at C:\Users\inrm\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
evalall at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:151
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:627
macro expansion at C:\Users\inrm\.julia\packages\Atom\cYxbS\src\eval.jl:36 [inlined]
#172 at .\task.jl:333
unknown function (ip: 00000000182BE893)
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\task.c:659
Allocations: 92015103 (Pool: 91992416; Big: 22687); GC: 79

you can find in the report that the errors happen in function svm_predict_values().

versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\inrm\AppData\Local\atom\app-1.43.0\atom.exe"  -a
  JULIA_FFTW_PROVIDER = MKL
  JULIA_NUM_THREADS = 4

I am using LIBSVM v0.4.0.

Thanks a lot if you can check it!

**Comment by helloinrm** [comment]
i am closing this issue in case of [crossposting](https://github.com/JuliaLang/julia/issues/35954).

**Comment by StefanKarpinski** [comment]
You should probably reopen this as it's much more likely that LIBSVM is the culprit here.
