### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by IainNZ** [mpastell/LIBSVM.jl#8]
Hi @simonster ,

Just tried to get someone set up with this on Windows. I tried dropping in the `.dll` from http://www.csie.ntu.edu.tw/~cjlin/libsvm/ but it reported "module not found" which is worrying - I have no idea if that `.dll` is 32-bit or 64-bit so thats not a great start. Have you had any experience with this?

**Comment by mpastell** [comment]
I have added a binary .dll that will get downloaded on build (only 64 bit for now), if somebody needs 32bit let me know.

**Comment by mpastell** [comment]
.dll has been added to v0.1.0
